Repository CUK-CAPSTONE/back-end, pull requests merged in 2024-05, with the labels that each got.

#34 CORS config
  src/main/java/com/hyunn/capstone/config/SwaggerConfig.java
  src/main/java/com/hyunn/capstone/config/WebConfig.java
  src/main/java/com/hyunn/capstone/controller/ImageController.java
  src/main/java/com/hyunn/capstone/controller/KakaoLoginController.java
  src/main/java/com/hyunn/capstone/controller/MessageController.java
  src/main/java/com/hyunn/capstone/controller/PrinterController.java
  src/main/java/com/hyunn/capstone/controller/UserController.java
  src/main/java/com/hyunn/capstone/controller/test/TestController.java
  src/main/java/com/hyunn/capstone/dto/request/ImageToTextRequest.java
  src/main/java/com/hyunn/capstone/dto/request/MessageRequest.java
  src/main/java/com/hyunn/capstone/dto/request/ThreeDimensionCreateRequest.java
  src/main/java/com/hyunn/capstone/dto/request/UserRequest.java
  src/main/java/com/hyunn/capstone/dto/response/ApiStandardResponse.java
  src/main/java/com/hyunn/capstone/dto/response/ErrorResponse.java
  src/main/java/com/hyunn/capstone/dto/response/ImageToTextResponse.java
  src/main/java/com/hyunn/capstone/dto/response/MessageResponse.java
  src/main/java/com/hyunn/capstone/dto/response/ThreeDimensionCreateResponse.java
  src/main/java/com/hyunn/capstone/dto/response/ThreeDimensionResponse.java
  src/main/java/com/hyunn/capstone/dto/response/UserResponse.java
  src/main/java/com/hyunn/capstone/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/hyunn/capstone/exception/handler/ImageExceptionHandler.java
  src/main/java/com/hyunn/capstone/exception/handler/KakaoLoginExceptionHandler.java
  src/main/java/com/hyunn/capstone/exception/handler/MessageExceptionController.java
  src/main/java/com/hyunn/capstone/exception/handler/PrinterServerExceptionHandler.java
  src/main/java/com/hyunn/capstone/exception/handler/UserExceptionHandler.java
  src/main/java/com/hyunn/capstone/service/ImageService.java
  src/main/java/com/hyunn/capstone/service/KakaoLoginService.java
  src/main/java/com/hyunn/capstone/service/MeshyApiService.java
  src/main/java/com/hyunn/capstone/service/MessageService.java
  src/main/java/com/hyunn/capstone/service/PrinterService.java
  src/main/java/com/hyunn/capstone/service/UserService.java
Labels: bug

#35 엔티티 수정 및 3D 프린터 통신 API 수정
  src/main/java/com/hyunn/capstone/controller/PrinterController.java
  src/main/java/com/hyunn/capstone/entity/Image.java
  src/main/java/com/hyunn/capstone/entity/Payment.java
  src/main/java/com/hyunn/capstone/exception/ErrorStatus.java
  src/main/java/com/hyunn/capstone/exception/PaymentNotFoundException.java
  src/main/java/com/hyunn/capstone/exception/handler/PrinterServerExceptionHandler.java
  src/main/java/com/hyunn/capstone/service/MessageService.java
  src/main/java/com/hyunn/capstone/service/PrinterService.java
Labels: enhancement

#37 카카오페이 단건 결제 구현 ( 결제 요청, 결제 승인 )
  src/main/java/com/hyunn/capstone/controller/KakaoPayController.java
  src/main/java/com/hyunn/capstone/dto/request/KakaoPayReadyRequest.java
  src/main/java/com/hyunn/capstone/dto/response/KakaoPayApproveResponse.java
  src/main/java/com/hyunn/capstone/dto/response/KakaoPayReadyResponse.java
  src/main/java/com/hyunn/capstone/service/KakaoPayService.java
Labels: enhancement, 이준수

#40 5/17 회의 후 작업
  README.md
  src/main/java/com/hyunn/capstone/controller/ImageController.java
  src/main/java/com/hyunn/capstone/controller/KakaoLoginController.java
  src/main/java/com/hyunn/capstone/controller/MessageController.java
  src/main/java/com/hyunn/capstone/controller/PrinterController.java
  src/main/java/com/hyunn/capstone/controller/UserController.java
  src/main/java/com/hyunn/capstone/dto/response/ImageToTextResponse.java
  src/main/java/com/hyunn/capstone/entity/Description.java
  src/main/java/com/hyunn/capstone/exception/DescriptionNotFoundException.java
  src/main/java/com/hyunn/capstone/exception/ErrorStatus.java
  src/main/java/com/hyunn/capstone/exception/PaymentNotFoundException.java
  src/main/java/com/hyunn/capstone/exception/handler/ImageExceptionHandler.java
  src/main/java/com/hyunn/capstone/repository/DescriptionJpaRepository.java
  src/main/java/com/hyunn/capstone/service/ImageService.java
  src/main/java/com/hyunn/capstone/service/KakaoLoginService.java
  src/main/java/com/hyunn/capstone/service/MeshyApiService.java
  src/main/java/com/hyunn/capstone/service/PrinterService.java
  src/main/java/com/hyunn/capstone/service/UserService.java
Labels: bug, documentation, enhancement

#42 3D 프린터 통신 수정 및 유저 별 결제 기록 API 추가
  README.md
  build.gradle
  src/main/java/com/hyunn/capstone/controller/KakaoPayController.java
  src/main/java/com/hyunn/capstone/controller/MessageController.java
  src/main/java/com/hyunn/capstone/controller/PrinterController.java
  src/main/java/com/hyunn/capstone/controller/UserController.java
  src/main/java/com/hyunn/capstone/controller/test/ImageDto.java
  src/main/java/com/hyunn/capstone/controller/test/PaymentDto.java
  src/main/java/com/hyunn/capstone/controller/test/TestController.java
  src/main/java/com/hyunn/capstone/dto/response/KakaoPayApproveResponse.java
  src/main/java/com/hyunn/capstone/dto/response/PaymentResponse.java
  src/main/java/com/hyunn/capstone/entity/Payment.java
  src/main/java/com/hyunn/capstone/exception/handler/KakaoPayExceptionHandler.java
  src/main/java/com/hyunn/capstone/repository/PaymentJpaRepository.java
  src/main/java/com/hyunn/capstone/repository/UserJpaRepository.java
  src/main/java/com/hyunn/capstone/service/ImageService.java
  src/main/java/com/hyunn/capstone/service/KakaoPayService.java
  src/main/java/com/hyunn/capstone/service/PrinterService.java
  src/main/java/com/hyunn/capstone/service/UserService.java
Labels: bug, documentation, enhancement, 조현태
