Repository CUK-CAPSTONE/back-end, pull requests merged in 2024-06, with the labels that each got.

#43 6/3일 프론트엔드 요청 처리
  README.md
  src/main/java/com/hyunn/capstone/controller/ImageController.java
  src/main/java/com/hyunn/capstone/dto/request/ThreeDimensionRequest.java
  src/main/java/com/hyunn/capstone/dto/response/ThreeDimensionCreateResponse.java
  src/main/java/com/hyunn/capstone/entity/Description.java
  src/main/java/com/hyunn/capstone/service/MeshyApiService.java
Labels: enhancement

#44 Meshy AI API 프롬포트 수정 및 OpenAI의 chatGPT를 활용한 이미지 분석 추가
  README.md
  src/main/java/com/hyunn/capstone/controller/OpenAIController.java
  src/main/java/com/hyunn/capstone/service/MeshyApiService.java
  src/main/java/com/hyunn/capstone/service/OpenAIService.java
Labels: documentation, enhancement, 조현태

#45 text_to_3D 반환값 수정 및 구조 변경
  README.md
  src/main/java/com/hyunn/capstone/config/AmazonS3Config.java
  src/main/java/com/hyunn/capstone/controller/ImageController.java
  src/main/java/com/hyunn/capstone/dto/request/ImageToTextRequest.java
  src/main/java/com/hyunn/capstone/dto/response/ImageToTextResponse.java
  src/main/java/com/hyunn/capstone/dto/response/KakaoPayReadyResponse.java
  src/main/java/com/hyunn/capstone/dto/response/MeshyAPIResponse.java
  src/main/java/com/hyunn/capstone/dto/response/PaymentResponse.java
  src/main/java/com/hyunn/capstone/dto/response/ThreeDimensionResponse.java
  src/main/java/com/hyunn/capstone/exception/UnauthorizedImageAccessException.java
  src/main/java/com/hyunn/capstone/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/hyunn/capstone/exception/handler/ImageExceptionHandler.java
  src/main/java/com/hyunn/capstone/exception/handler/KakaoPayExceptionHandler.java
  src/main/java/com/hyunn/capstone/exception/handler/PrinterServerExceptionHandler.java
  src/main/java/com/hyunn/capstone/service/MeshyApiService.java
  src/main/java/com/hyunn/capstone/service/UserService.java
Labels: bug, documentation, enhancement, 조현태

#48 결제 승인 페이지 html로 구현 ( 결제 취소 버튼은 미구현)
  build.gradle
  src/main/java/com/hyunn/capstone/controller/KakaoPayController.java
  src/main/resources/templates/paymentSuccess.html
Labels: enhancement, 이준수

#49 결제 완료 페이지 수정 및 결제 중 오류 처리
  src/main/java/com/hyunn/capstone/controller/KakaoPayController.java
  src/main/java/com/hyunn/capstone/service/KakaoPayService.java
  src/main/resources/templates/PaymentFail.html
  src/main/resources/templates/PaymentSuccess.html
Labels: bug, enhancement, 조현태

#50 닫기 버튼 수정
  src/main/resources/templates/PaymentFail.html
  src/main/resources/templates/PaymentSuccess.html
Labels: bug, 조현태

#51 닫기 버튼 수정
  src/main/java/com/hyunn/capstone/repository/PaymentJpaRepository.java
  src/main/java/com/hyunn/capstone/service/KakaoPayService.java
  src/main/resources/templates/PaymentFail.html
  src/main/resources/templates/PaymentSuccess.html
Labels: bug, enhancement, 조현태

#52 창 닫기 버튼 삭제
  src/main/java/com/hyunn/capstone/service/KakaoPayService.java
  src/main/resources/templates/PaymentFail.html
  src/main/resources/templates/PaymentSuccess.html
Labels: bug, 조현태

#53 시간 형식 수정
  src/main/resources/templates/PaymentSuccess.html
Labels: bug, 조현태

#54 BaseEntity 수정
  src/main/java/com/hyunn/capstone/entity/BaseEntity.java
  src/main/resources/templates/PaymentSuccess.html
Labels: bug, 조현태

#55 카카오 로그인 부터 결제까지 한번에 처리
  src/main/java/com/hyunn/capstone/controller/KakaoLoginController.java
  src/main/java/com/hyunn/capstone/controller/KakaoPayController.java
  src/main/java/com/hyunn/capstone/repository/ImageJpaRepository.java
  src/main/java/com/hyunn/capstone/service/KakaoPayService.java
  src/main/resources/templates/KakaoLoginAndPay.html
Labels: bug, enhancement, 조현태

#56 최신순으로 반환
  src/main/java/com/hyunn/capstone/repository/ImageJpaRepository.java
  src/main/java/com/hyunn/capstone/repository/PaymentJpaRepository.java
  src/main/java/com/hyunn/capstone/service/UserService.java
Labels: bug, 조현태

#57 glb 지정 코드 추가
  src/main/java/com/hyunn/capstone/controller/ImageController.java
Labels: 조현태

#58 glb 지정 코드 추가
  src/main/java/com/hyunn/capstone/controller/ImageController.java
Labels: 조현태

#61 메인 페이지 수정
  src/main/java/com/hyunn/capstone/service/MessageService.java
Labels: enhancement, 조현태

#62 README 포트폴리오 작업
  README.md
  src/main/java/com/hyunn/capstone/service/MessageService.java
Labels: documentation, 조현태

#63 README 수정 최종본
  README.md
Labels: documentation, 조현태
